JSON file generator tests
ranking-agent/json-schema-fuzz pull request #28
Opened 2021-03-02 18:23 UTC by alongreyber

2021-03-02 19:20 UTC, patrickkwang requested changes

2021-03-02 19:20 UTC, patrickkwang commented on tests/test_generator.py
> +    for value in generated_json_values:
We can make this more concise and more efficient in failure cases by combining the validation loop and the generation list comprehension.

2021-03-02 20:33 UTC, patrickkwang commented
Since our tests are actually stochastic, it may not be simple to reproduce a failed test (due to a real bug). Do we get enough information from pytest to at least recall the specific instance that failed validation?

2021-03-02 20:43 UTC, alongreyber commented
That is a good point. How about we add `random.seed(0)` to the top of the test file? I just tried it and it produces the same values every time.

2021-03-02 20:46 UTC, patrickkwang commented
That's an option. I'm not opposed to the tests being irreproducible _if_ we get enough information to identify the offending instance.

2021-03-02 21:06 UTC, alongreyber commented
Should be fixed now. Validation errors will now log the instance that was being validated.

2021-03-03 13:54 UTC, patrickkwang approved these changes

2021-03-03 13:55 UTC, merged